### ISSUE TITLE
Mapping av OIDC authLevel (acr) til SAML authLevel

### ISSUE THREAD

**Issue by espengjostol** [navikt/gandalf#30]
I PSELV (Din pensjon) har vi integrasjon mot Soap-APIet til bl.a. DKIF.
OIDC-token veksles til SAML-token via REST-STS (gandalf).
DKIF-kallet fungerer i FSS, men ikke i SBS.
Problemet er at DKIF krever at `authenticationLevel` i SAML-tokenet må være et tall, mens verdien som brukes er "Level4".
Derfor ønskes følgende kodeendring i gandalf:
I `AccessTokenIssuer.kt` endre
```
samlObj.authenticationLevel = oidcObj.authLevel
```
til
```
samlObj.authenticationLevel = getAuthenticationLevel(oidcObj)
```
og følgende funksjon legges til:
```
    fun getAuthenticationLevel(oidcObj: OidcObject): String {
        return when {
            oidcObj.authLevel.equals("Level3") -> "3"
            oidcObj.authLevel.equals("Level4") -> "4"
            else -> DEFAULT_SAML_AUTHLEVEL
        }
    }
```

**Comment by ybelMekk** [comment]
Verdien som brukes er fra original-tokenet, alltså Azure b2c tokenet som byttes inn.

**Comment by ybelMekk** [comment]
@espengjostol er i test miljø nå. så du kan teste

**Comment by espengjostol** [comment]
@ybelMekk Det virker fint, takk!
